version: '3.7'

services:
  python-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - lead_network
    
networks:
  lead_network:
    external: true