global:
  scrape_interval: 2s

scrape_configs:
  - job_name: rabbitmq_metrics
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    static_configs:
      - targets: ['rabbitmq:15692']
